[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "statusbar"
version = "0.1.0"

[dependencies]
alsa = "^0.2.0"
#json = "^0.11.13"
nix = "^0.10.0"
#password-store = "^0.2.0"
rem = "^0.1.0"
time = "^0.1.39"
#tls-api = "^0.1.14"
#tls-api-openssl = "^0.1.14"
